export enum Icon {
  PROGRAMMING_LANGUAGE = '/icons/programming-language.svg',
  TOOL = '/icons/tool.svg',
  BASH = '/icons/bash.svg',
  FRAMEWORK = '/icons/framework.svg',
  VUE = '/icons/vue.svg',
  REACT = '/icons/react.svg',
  HTML_CSS = '/icons/html-css.svg',
  DATABASE = '/icons/database.svg',
  DEVELOPMENT = '/icons/development.svg',
  JAVASCRIPT = '/icons/javascript.svg',
  NUXT = '/icons/nuxt.svg',
  JAVASCRIPT_DEV_TOOLS = '/icons/js-dev-tools.svg',
  DOCKER = '/icons/docker.svg',
  SCALA = '/icons/scala.svg',
  PYTHON = '/icons/python.svg',
  KOTLIN = '/icons/kotlin.svg',
  JAVA = '/icons/java.svg',
  TYPESCRIPT = '/icons/typescript.svg'
}
